# Configuracoes do Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Versoes do Minecraft e mappings
minecraft_version=1.21.4
neo_version=21.4.0-beta
neo_version_range=[21.4.0-beta,)
loader_version_range=[4,)

# Parchment (nomes de parametros legiveis no codigo)
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.01.19

# Dados do nosso mod
mod_id=omnitrix
mod_name=Omnitrix
mod_license=MIT
mod_version=0.0.1
mod_group_id=com.bendez.omnitrix
mod_authors=Voce
mod_description=Um mod fiel ao Ben 10 Classico. Encontre o Omnitrix e transforme-se em 10 alienigenas!
