plugins {
    id 'com.android.application'
}

android {
    namespace 'com.exemplo.mkbot'
    compileSdk 34
    buildToolsVersion "34.0.0"

    defaultConfig {
        applicationId "com.exemplo.mkbot"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'org.jetbrains.kotlin') {
            details.useVersion '1.8.22'
            details.because 'Forcar versao unica do Kotlin stdlib'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
}
