name: Build Omnitrix Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Compilar o mod
        run: gradle build --no-daemon

      - name: Enviar o mod compilado
        uses: actions/upload-artifact@v4
        with:
          name: omnitrix-mod
          path: build/libs/*.jar
          
